Feature/RW1
mike-live/RWGame pull request #10
Opened 2020-04-04 13:41 UTC by SermanVS

Добавил свайп обновления, при котором на 2 секунды крутится колёсико с картинкой, обновляется список игр, по-моему по красоте вышло. Только меня опять пугает Resource.designer.cs, не сломалось бы что-то, если его убрать из коммита

2020-04-06 10:19 UTC, mike-live requested changes

2020-04-06 10:19 UTC, mike-live commented on RWGame/RWGame/UserPage.cs
> +            downSwipeGesture.Swiped += async delegate
Жест работает только сверху экрана почему-то. Наверное там стоит перехватчик жеста на списке, и когда по нему провожу не работает. Наверное, это сложно чиниться с нормальным поведением списка. Список тоже надо листать когда в нем много итемов.

2020-04-06 10:19 UTC, mike-live commented on RWGame/RWGame/UserPage.cs
> +                await UpdateGameList();
Подозреваю, что он сначала сделает update, а потом будет крутить картинку. В идеале бы чтобы это как-то одновременно выполнялось бы. Видимо тебе надо почитать про асинхронное программирование и про await/async, чтобы научиться так делать.

2020-04-06 10:19 UTC, mike-live commented on RWGame/RWGame/UserPage.cs
> +            userprofilStackLayout.Children.Add(updateImage);
Видимо эта штука заставляет сделать так, чтобы все уползло вниз. Попробуй подумать над тем, как сделать поверх. Типа как в chrome. Либо сделать так, чтобы кнопочки не уползали бы вниз.

2020-04-06 10:19 UTC, mike-live commented on RWGame/RWGame/UserPage.cs
> +                Source = "update30.png"
Картинке не хватает high quality. Там фон на ней прозрачный сделать и разрешение повыше.

2020-04-10 14:42 UTC, SermanVS commented
Поменял картинку, пофиксил свап. Работает всё так же только на верхней части. У меня в списке 60 игр примерно, и не думаю, что где-то вообще  на списках работает свайп, сталкивался уже с таким поведением

2020-04-11 10:53 UTC, mike-live commented
![](https://github.trello.services/images/mini-trello-icon.png) [RW1. Кнопка обновления страницы с играми. И жест как для обновления страницы в мобильном браузере](https://trello.com/c/E8juR4vg/20-rw1-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B0-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B-%D1%81-%D0%B8%D0%B3%D1%80%D0%B0%D0%BC%D0%B8-%D0%B8-%D0%B6%D0%B5%D1%81%D1%82-%D0%BA%D0%B0%D0%BA-%D0%B4%D0%BB%D1%8F-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B-%D0%B2-%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D0%BC-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B5)

2020-04-29 13:14 UTC, merged