MVVM standings
mike-live/RWGame pull request #18
Opened 2020-09-29 19:29 UTC by SermanVS

Split StandingsPage so that it fits into MVVM pattern and added auxillary classes

2020-09-29 20:42 UTC, mike-live requested changes

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/Enums/Emojis.cs
> +﻿using System;
Папочку Enums ты добавил по аналогии с Classes. Но мы так не хотим. Это не самый лучший способ разделения информации по названиям возможностей языка. Разделение в идеале должно быть по MVVM или по сущностям смысловым в проекте. Поэтому Enums надо переименовать. Можно пока назвать Emojis, либо переложить во ViewModels так как по смыслу это помощник именно ViewModels.

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/Enums/Emojis.cs
> +﻿using System;
В остальном пока ок, но вероятно нам понадобится вынести коды символов отдельно. И когда будем делать для apple обратить внимание, как они отображаются. И если нам не понравится, то переделать на картинки.

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/ViewModels/StandingsPageViewModel.cs
> +                    return Color.FromHex("#1039bafa");
Magic number

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/ViewModels/StandingsPageViewModel.cs
> +            switch (position)
Подумай можно ли сделать без switch

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/ViewModels/StandingsPageViewModel.cs
> +                if (standingsModel.standingsListViewRecords != null)
Немного странно, что здесь создаётся объект. Кажется, что он должен быть хранимый, а не временный.

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/ViewModels/StandingsPageViewModel.cs
> +                var temp = new ObservableCollection<StandingViewCellElement>();
Имя temp в общем случае лучше не использовать по возможности. В данном случае вроде не жалко прям явно обращаться к объекту.

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/ViewModels/StandingsPageViewModel.cs
> +                var temp = new ObservableCollection<StandingViewCellElement>();
А здесь вообще нужен set?

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/Views/StandingsPage.xaml
> +                   TextColor="#0099e6"
Magic number. Theme

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/Views/StandingsPage.xaml
> +             BackgroundColor="White"
Theme

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/Views/StandingsPage.xaml
> +             BackgroundImageSource="background_2_art_1.png">
Theme

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/Models/StandingsModel.cs
> +    public class StandingViewCellElement
Не угадал, это сущность для ViewModel, а не для Model. Все методы говорят, как должны быть представлены и отформатированы данные, а не просто возвращает данные. Из-за этого у тебя расплодился этот класс дублером во ViewModel.

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/Models/StandingsModel.cs
> +    public class StandingViewCellElement
Собственно даже название класса говорит, что оно про отображение, а не про сами данные

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/Models/StandingsModel.cs
> +    public class StandingViewCellElement
Если ты всё же хочешь observablecollection, то тебе придется сделать её только про данные и назвать соответствующим образом.
Например вот эта строчка не про данные: return "#" + playerRank.ToString();

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/Models/StandingsModel.cs
> +    public class StandingViewCellElement
Поищи, как можно обмениваться инфой между двумя observablecollection. Скорее всего можно делать это проксировано, чтобы хранение было только в модельке и синтаксис был бы прозрачно написан без создания отдельной коллекции на каждый get. (Не обещаю, что так бывает, но вдруг) Там она же не просто так называется observable

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/Models/StandingsModel.cs
> +using Xamarin.Forms;
Плохо что в модели есть Forms!

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/ViewModels/StandingsPageViewModel.cs
> +                        return Color.FromHex("#95f7f9a0");
Magic Number. Theme

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/ViewModels/StandingsPageViewModel.cs
> +                manPerformanceCenterLabelText = ManVsBot.PerformanceCenter;
Наверное можно это возвращать в get поля, а не при update менять. Иначе немного смысл property немного теряется.

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/ViewModels/StandingsPageViewModel.cs
> +    class StandingsData : INotifyPropertyChanged
Название говорит, что это данные и обманывает нас. Либо данные должны хранится в модели, либо этот класс отвечает не за данные

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/ViewModels/StandingsPageViewModel.cs
> +        public StandingsModel standingsModel { get; set; }
Странно, что public. Ты вроде ратовал за то, чтобы нельзя был использовать его из вне из всяких View

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/ViewModels/StandingsPageViewModel.cs
> +            OnPropertyChanged();
В идеале эта штука должна выглядеть прозрачно. То есть изменения в модели автоматически ведут к изменениям во ViewModel и View, без дерганий дополнительных OnPropertyChanged. Посмотри штуку которую я говорил fody weavers. Она у нас уже есть в проекте. Но ей надо грамотно воспользоваться

2020-09-29 20:42 UTC, mike-live commented on RWGame/RWGame/Views/StandingsPage.xaml
> +            <!-- Temporary! Change text to Binding later if we want to use this view for different standings. -->
Здесь тоже можно делать region. Научись

2020-10-01 21:39 UTC, SermanVS commented on RWGame/RWGame/ViewModels/StandingsPageViewModel.cs
> +        public StandingsModel standingsModel { get; set; }
Поменял на private, всё ещё работает, это я по неопытности все сделал public

2020-10-01 21:40 UTC, SermanVS commented on RWGame/RWGame/ViewModels/StandingsPageViewModel.cs
> +            switch (position)
Сделал через тернарный

2020-10-01 21:52 UTC, SermanVS commented on RWGame/RWGame/ViewModels/StandingsPageViewModel.cs
> +                var temp = new ObservableCollection<StandingViewCellElement>();
set оказался не нужен

2020-10-01 22:21 UTC, SermanVS commented on RWGame/RWGame/Models/StandingsModel.cs
> +using Xamarin.Forms;
Это я специально оставил проверить, заметишь ли ты, на самом деле они там не используются))

2020-10-01 22:41 UTC, SermanVS commented on RWGame/RWGame/ViewModels/StandingsPageViewModel.cs
> +                manPerformanceCenterLabelText = ManVsBot.PerformanceCenter;
Можно, но у меня получилось сделать только через OnPropertyChanged в методе обновления

2020-10-01 22:48 UTC, SermanVS commented on RWGame/RWGame/Views/StandingsPage.xaml
> +            <!-- Temporary! Change text to Binding later if we want to use this view for different standings. -->
StackOverflow говорит, что нужно расширение для студии качать, но т.к. все элементы можно коллапсить итак, то не уверен, что нужны region в xaml

2020-10-02 09:13 UTC, mike-live commented
![](https://github.trello.services/images/mini-trello-icon.png) [MVVM standings](https://trello.com/c/FIqWmvZE/53-mvvm-standings)

2020-11-22 21:32 UTC, mike-live approved these changes
Fine!

2021-04-02 13:22 UTC, merged