MVVM history... and much much more
mike-live/RWGame pull request #19
Opened 2020-10-26 01:33 UTC by SermanVS

Тут рабочий UserPage (который в какой-то момент у меня опять уплыл вниз. Полагаю, это какая-то бага студии, что она так билдит у меня, что с N-го билда список улезает вниз, ибо я помню, что в момент, когда это произошло, я не менял ничего, связанного с этим) без гайда.
Рабочий GamesHistoryPage, без компромисов.
Перерисованные картинки тоже тут, ну и небольшие эдиты в различных файлах, без которых нельзя было.

2020-10-26 10:43 UTC, SermanVS commented on RWGame/RWGame/ViewModels/UserViewModel.cs
> +            await Navigation.PushAsync(UserModel.StandingsPage);
Вызывается старый StandingsPage

2020-11-01 16:54 UTC, mike-live requested changes

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/Views/UserPage.xaml
> +                            <ColumnDefinition Width="1*"/>
Bug fix: 1* заменить на звездочку

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/Views/UserPage.xaml
> +                        <ColumnDefinition Width="3*"/>
Bug fix: 3* заменить на *

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/Models/UserModel.cs
> +        public RealPlayerChoicePage RealPlayerChoicePage { get; set; }
Вроде модель, а откуда-то знает про Page. Она ничего не должна знать о страницах. Никаких. Остальные модели аналогично.

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/ViewModels/GameHistoryViewModel.cs
> +            GamesList = GameHistoryModel.GamesList;
Кажется GamesList на не нужен как Property совсем. А если нужен, то это странно. Проверь зачем он как property

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/ViewModels/UserViewModel.cs
> +                if (new[] { GameStateEnum.NEW, GameStateEnum.CONNECT, GameStateEnum.START }.Contains(game.GameState))
Какая-то длинная строка. Лучше, наверное, её разбить на несколько, чтобы понятно было, что в ней происходит.

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/ViewModels/UserViewModel.cs
> +        public ElementsOfViewCell(Game _game)
Вероятно здесь нет необходимости в нижнем подчеркивании. Возможно можно использовать this в крайнем случае

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/ViewModels/UserViewModel.cs
> +        public Game game { get; set; }
Наверное не public.

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/ViewModels/UserViewModel.cs
> +        public async void UpdateGameList()
Кажется этот код повторяется. Можно ли сделать его общим?

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/Views/UserPage.xaml
> +﻿<?xml version="1.0" encoding="utf-8" ?>
Где-то надо добавить отступ для списка, иначе он упирается в левый край.

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/Views/UserPage.xaml
> +<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
Выравнивание второго никнейма в списке исходно было по правому краю. Сейчас по левому. Если это случайно, то верни.

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/Views/UserPage.xaml
> +             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
Если кликнуть на item и не отпускать, то видно, что у лейблов и всего что там внутри белый фон. Если можно его прозрачным, то наверное было бы хорошо. Если было задумано с белым фоном, то пиши почему.

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/Views/UserPage.xaml
> +             xmlns:skia="clr-namespace:SkiaSharp.Views.Forms;assembly=SkiaSharp.Views.Forms"
Попробуй сделать кнопочки friend и bot, чтобы кликабельность была у целого прямоугольничка с кнопкой и картинкой. Пример, возможно не самый полезный, есть на странице логина. Там google play кнопка

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/ViewModels/GameHistoryViewModel.cs
> +            await TaskUpdateGameList();
Проверь, сколько раз этот метод вызывается при переходе на эту страницу. Должен только один раз. И замерь время работы этого метода. Ну по честному, кодом прям.

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/Views/GameHistoryPage.xaml
> +                      IsRefreshing="{Binding GameHistoryDisplayData.IsCustomListViewRefreshing}"
А что даёт эта штука? Было бы прикольно, чтобы он серым, например, подсвечивал текст в ListView, если он старый, а новый ещё грузится. (Но возможно это потом)

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/ViewModels/GameHistoryViewModel.cs
> +            IsCustomListViewRefreshing = false;
В будущем было бы клёво, чтобы при переключении вкладок не происходила перезагрузка списка. Но при переходе с других страниц, типа если игру сыграл, то надо обновить. 
Ещё видимо у них одинаковый список игр на самом деле. И было бы клёво, чтобы они его делили на двоих, чтобы не ходили 2 раза за списком. И если у одного обновился то и у другого тоже.

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/ViewModels/UserViewModel.cs
> +        public string Title { get { return "Sarted Games"; } }
Наверное, если храним константу, то есть более простой вариант:
public string Title { get; } = "Sarted Games";
Ниже там аналогичные примеры есть.
Ну и плюс опечатку поправь.
Не знаю правда зачем ты их сюда вынес. Но да бог с ним. Потом всё равно будет по другому, когда в xml вынесем.

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/Views/UserPage.xaml
> +             xmlns:behaviorsPack="clr-namespace:Xamarin.Forms.BehaviorsPack;assembly=Xamarin.Forms.BehaviorsPack"
А фон сверху где вкладки ты кстати решил оставить синим специально? Тебе так больше понравилось? Или не думал над ним? В общем подумай над ним.

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/Views/UserPage.xaml
> +              HorizontalOptions="FillAndExpand"
Здесь по файлу почему-то проблемы с выравниванием. Почини.

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/Models/UserModel.cs
> +}
Добавь лишнюю строку, чтобы он не рисовал всякие символы тут не красивые.

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/Models/UserModel.cs
> +        public double PerformanceBorder {get; set; }
Пробел потерялся

2020-11-01 16:54 UTC, mike-live commented on RWGame/RWGame/Models/UserModel.cs
> +            PerformanceCenter = Math.Round(PlayerInfo?.PlayerStatistics.PerformanceCenterVsBot.Value ?? 0);
Зарегай новый аккаунт и проверь, что всё происходит, как и ожидается.

2020-11-01 17:04 UTC, SermanVS commented on RWGame/RWGame/Views/GameHistoryPage.xaml
> +                      IsRefreshing="{Binding GameHistoryDisplayData.IsCustomListViewRefreshing}"
Если список не скажет всем, что он обновился, то он не перестанет обновляться. Нужная штука, короче

2020-11-01 17:06 UTC, SermanVS commented on RWGame/RWGame/ViewModels/UserViewModel.cs
> +        public string Title { get { return "Sarted Games"; } }
Ну хардкодить слова в xml мне кажется не лучшей идеей, потому что они там сольются с текстом и потеряются ещё. 
Не вижу какой-то выгоды от public string Title { get; } = "Sarted Games"; по сравнению с текущим вариантом, но ок

2020-11-01 17:07 UTC, SermanVS commented on RWGame/RWGame/Views/UserPage.xaml
> +              HorizontalOptions="FillAndExpand"
Там smart indent посчитал, что так правильно (Ctrl+A, Ctrl+K, Ctrl+F)

2020-11-01 17:20 UTC, SermanVS commented on RWGame/RWGame/Models/UserModel.cs
> +}
![Screenshot_1](https://user-images.githubusercontent.com/19808031/97809715-b0595180-1c7f-11eb-8295-135b2a931e4f.png)

2020-11-01 17:20 UTC, SermanVS commented on RWGame/RWGame/Models/UserModel.cs
> +}
Не вижу там символов каких-то

2020-11-01 17:54 UTC, SermanVS commented on RWGame/RWGame/ViewModels/UserViewModel.cs
> +        public Game game { get; set; }
Nope, он публичным нужен, чтобы вызываться из других мест (это нужно, чтобы получить GameId).
Можно, конечно, заранее его получать в специальную проперти, но стоит ли?

2020-11-01 17:59 UTC, SermanVS commented on RWGame/RWGame/ViewModels/UserViewModel.cs
> +        public async void UpdateGameList()
Не думаю

2020-11-01 18:50 UTC, SermanVS commented on RWGame/RWGame/Views/UserPage.xaml
> +             xmlns:skia="clr-namespace:SkiaSharp.Views.Forms;assembly=SkiaSharp.Views.Forms"
Все кнопка переделывать под Grid? Стоит ли оно того, если кликабельна сама картинка + текст под ней

2020-11-01 19:28 UTC, SermanVS commented on RWGame/RWGame/ViewModels/GameHistoryViewModel.cs
> +            await TaskUpdateGameList();
Он вызывается не при загрузке страницы. При загрузке вызывается Task, а эта штука только при PullToRefresh и когда выходит с GameField.
Нужный метод Task вызывается один раз. Намерил 0.47 секунды, но хз точно ли так, может я ошибся, но похоже на правду

2020-11-01 23:49 UTC, SermanVS commented on RWGame/RWGame/Models/UserModel.cs
> +            PerformanceCenter = Math.Round(PlayerInfo?.PlayerStatistics.PerformanceCenterVsBot.Value ?? 0);
Всё падает(

2020-11-02 07:24 UTC, mike-live commented on RWGame/RWGame/Models/UserModel.cs
> +}
При просмотре коммита на github он рисует красный кружок перечеркнутый.

2020-11-02 07:35 UTC, mike-live commented on RWGame/RWGame/ViewModels/UserViewModel.cs
> +        public Game game { get; set; }
Сделай property для idGame. Иначе это типа данные модельки.

2020-11-02 07:38 UTC, mike-live commented on RWGame/RWGame/Views/UserPage.xaml
> +             xmlns:skia="clr-namespace:SkiaSharp.Views.Forms;assembly=SkiaSharp.Views.Forms"
Какая реализация это на твоё усмотрение. А вот если можно сделать, чтобы при нажатии подсвечивалась не только картинка, но ещё и подпись захватывало, то будет клёво.

2020-11-02 07:48 UTC, mike-live commented on RWGame/RWGame/ViewModels/GameHistoryViewModel.cs
> +            await TaskUpdateGameList();
Ну я имею ввиду сколько раз вызывается TaskGetGamesList при переходе на страницу проверь.

2020-11-02 11:30 UTC, SermanVS commented on RWGame/RWGame/ViewModels/GameHistoryViewModel.cs
> +            await TaskUpdateGameList();
Ну вот один раз, как и должен)

2020-11-02 11:42 UTC, SermanVS commented on RWGame/RWGame/Models/UserModel.cs
> +        public RealPlayerChoicePage RealPlayerChoicePage { get; set; }
Сложно. Для создания страницы нужен serverWorker, который мы можем использовать только в модели

2020-11-02 12:35 UTC, mike-live commented on RWGame/RWGame/Models/UserModel.cs
> +        public RealPlayerChoicePage RealPlayerChoicePage { get; set; }
Давай в этом месте я пока дам поблажку и разрешу не использовать, но передавать serverWorker для конструирования страниц из ViewModel. В будущем мы просто сделаем один статический класс для него и не будем его никуда передавать. В этом месте проблема отпадёт.

2020-11-02 13:12 UTC, SermanVS commented on RWGame/RWGame/Models/UserModel.cs
> +            PerformanceCenter = Math.Round(PlayerInfo?.PlayerStatistics.PerformanceCenterVsBot.Value ?? 0);
Починил

2020-11-02 13:13 UTC, SermanVS commented on RWGame/RWGame/Models/UserModel.cs
> +        public RealPlayerChoicePage RealPlayerChoicePage { get; set; }
Ну типа починил, но теперь используется serverWorker во ViewModel. Пока что не вижу способа вынести это в какое-то правильное место

2020-11-11 10:46 UTC, mike-live requested changes
Падает, если зайти новым пользователем и перейти на страницу с историей игр судя по всему. Проверь этот момент. Ну и там от нового пользователя весь функционал проверь соответственно.

2020-11-11 10:46 UTC, mike-live commented on RWGame/RWGame.Android/RWGame.Android.csproj
> +    <None Include="..\..\.editorconfig">
Какой-то editorconfig появился. Не понятно что это, зачем и почему нет соответствующего файла к нему. Выясни, пожалуйста, что это за фигня такая вылезла.

2020-11-11 10:46 UTC, mike-live commented on RWGame/RWGame/Views/UserPage.xaml
> +              HorizontalOptions="FillAndExpand"
Мне кажется smart indent ничего не сделал вообще. Вроде если сделать руками выравнивание, то smart indent его потом не ломает. Поэтому сделай, чтобы оно норм было.

2020-11-11 10:46 UTC, mike-live commented on RWGame.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Solution Items", "Solution Items", "{3CDBD2E1-7A08-459D-8CCE-C03AF075E52B}"
Какая-то шляпа. Если можно убрать, то надо убрать. Либо выяснить что это и зачем

2021-04-02 13:22 UTC, merged