Ready mvvm branches
mike-live/RWGame pull request #21
Opened 2020-11-29 08:13 UTC by SermanVS

Merged 3 mvvm branches into this one for testing

2021-03-14 14:29 UTC, mike-live requested changes
Местами я пишу "должно быть в модельке", но подразумеваю должно быть либо во ViewModel либо в Model и надо подумать уместно ли в Model по смыслу или всё же это ViewModel.

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/ViewModels/GameFieldViewModel.cs
> +                return (Game.GameSettings.Goals[Game.IdPlayer] == "center") ?
Используй GameGoal

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +                return (ViewModel.Game.GameSettings.Goals[ViewModel.Game.IdPlayer] == "center") ?
GameGoal

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            if (ViewModel.CanAnimate)
CanAnimate непонятно зачем нужен сейчас

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            InfoTurnLabel.Text = "Wait...";
Binding InfoTurnLabel.Text на текущее состояние от CanMakeTurn, который вернёт нужную фразу. Тогда этой строчки не будет

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            ViewModel.AddToTrajectory();
Должен случаться автоматически в модели.

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            GameControls.ViewModel.ChosenTurn = -1;
ChosenTurn - property в View, которое завязано на ViewModel.ChosenTurn и при изменении делает либо FadeChosenTurn либо наоборот подсвечивает кнопку. А сам ChosenTurn по идее сбрасывается в модели, после того как она обновилась.

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            ViewModel.NumTurns = ViewModel.GameStateInfo.LastIdTurn;
Это должно происходить в Model, всё остальное через Binding

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            GameScoreLabel.Text = ViewModel.NumTurns.ToString();  // Is it okay?
Binding

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            canvasView.InvalidateSurface();
Эта штука на Binding события, которое генерирует Model. Типа ход закончился. Реализуется с помощью Dependency Injection. Могу пример привести, если непонятно как это сделать

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            ViewModel.CheckEnd();
Аналогично Model генерирует событие, что игра закончилась. И ViewModel на событие сделает нужное действие.

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            InfoTurnLabel.Text = "Make turn!";  // Is it okay?
Binding

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            GameControls.ViewModel.CanMakeTurn = true;
Binding, Аналогично Model этим занимается

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +        public async void UpdateState()
В итоге UpdateState не должен существовать. Он будет происходить автоматически за счёт того, что в модельке что-то меняется

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +                ViewModel.NumTurns--;
Эта плохая строчка. От него надо совсем избавиться. То есть моделька должна в NumTurns поддерживать гарантировано верное значение числа шагов и никто кроме модельки не должен изменять его.

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +                InfoTurnLabel.Text = "Moves history";
Binding

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            if (ViewModel.GameStateInfo.GameState != GameStateEnum.END)
Аналогично должен быть DI (Dependency Injection). То есть где-то в модельке при создании провериться GameState и если он END, то моделька сгенерит событие, которое в дальнейшем заставит GameControls создаться и что там ещё надо. Тогда логика действий уходит из View и остаётся только отрисовка. При этом сама моделька не знает, что будет какая-то отрисовка. Она просто говорит, что GameState END, а дальше View сама разберется как на это реагировать

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +        public void MergeBitmaps(SKCanvas canvas, SKBitmap bitmap1, SKBitmap bitmap2, int width, int height,
Этот метод в helpers куда-нибудь. Он вообще никакого отношения ко View не имеет.

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            ViewModel.ChosenTurn = id;
Это в Model должно случиться

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            if (!ViewModel.CanMakeTurn)
Тут очень много строчек ViewModel.* сделай то сё. По идее всё это должно происходить не здесь.

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            CanvasViewField.InvalidateSurface();
На InavlidateSurface какой-то Action надо повесить и отдать этот action во ViewModel например (ну то есть указатель на функцию отдать внутрь). Технически ViewModel ничего не будет знать о том, как именно работает этот метод. Но сможет когда нужно его дёргать. А дёргать ViewModel его будет при изменении ChosenTurn видимо.

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            if (ViewModel.GameStateInfo.GameState == GameStateEnum.WAIT)
Этот кусок и ниже это тоже явно не деятельность View

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +                ControlsImages[i / 2, i % 2] = SKBitmap.Decode(Helper.getResourceStream("Images." + ViewModel.ControlsImagesNames[dir] + ".png"));
Разбить на 2 строки

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            ViewModel.FillGameTrajectory();
Наверное он и сам может этот сделать и не надо его из View попинывать

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +        async void MakeTurn(int id)
По идее здесь должен остаться только вызов MakeTurnAndWait примерно

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Models/GameFieldModel.cs
> +        public string InfoTurnLabelText
Это частично ViewModel кажется. Надписей в модельке по идее не должно быть. Но моделька должна возвращать состояние. Enum можешь завести например

2021-03-14 14:29 UTC, mike-live commented on RWGame/RWGame/Models/GameFieldModel.cs
> +        public int MarginX { get; set; } = 100;
Наверное вот эти 4 это ты перестарался =) (возможно я что-то не так сказал) Они наверное заданы в пикселях вообще (уточни). А значит, наверное, во ViewModel хотя бы.

2021-03-30 10:26 UTC, mike-live requested changes

2021-03-30 10:26 UTC, mike-live commented on RWGame/RWGame.iOS/Entitlements.plist
> +		<string>$(AppIdentifierPrefix)com.companyname.RWGame</string>
По идее нас должны звать scigames, а не companyname

2021-03-30 10:26 UTC, mike-live commented on RWGame/RWGame.iOS/Info.plist
> +	<string>com.companyname.RWGame</string>
И в других местах тоже

2021-03-30 10:26 UTC, mike-live commented on RWGame/RWGame.iOS/RWGame.iOS.csproj
> +    <CodesignKey>Apple Development: Sergei Tikhomirov (S99WRDW6YL)</CodesignKey>
Правда ли, что это не секретная информация, и её можно класть в открытый репозиторий?

2021-03-30 10:26 UTC, mike-live commented on RWGame/RWGame/Models/GameFieldModel.cs
> +        public InfoStringsEnum InfoTurnLabelText
В модельке по идее не должно быть слов про label 
Наверное, имеет смысл переименовать InfoTurnLabelText в TurnState. То есть у тебя эта штука говорит о состоянии возможности совершения хода. И InfoStringsEnum аналогично. То есть в модели это должно быть не про строки, а про состояние. 

MAKE_FIRST_TURN -> FIRST_TURN
MAKE_TURN -> TURN
MOVES_HISTORY -> END

А вот во Viewmodel по ним ты уже определяешь, что надо человеку сказать, что там "Moves history" и остальные фразочки.

2021-03-30 10:26 UTC, mike-live commented on RWGame/RWGame/ViewModels/GameFieldViewModel.cs
> +            GameScoreLabelText = GameFieldModel.NumTurns.ToString();
А почему эти 2 штуки не сделаны через property? Давай сделаем. Вроде всё остальное ты сделал через property

2021-03-30 10:26 UTC, mike-live commented on RWGame/RWGame/ViewModels/GameFieldViewModel.cs
> +            InfoTurnLabelText = InfoStringsEnum.WAIT.ToDescriptionString();
Это какая-то странная вещь. А через property нельзя автоматически чтобы пробрасывалось?

2021-03-30 10:26 UTC, mike-live commented on RWGame/RWGame/ViewModels/GameFieldViewModel.cs
> +            if (IsFinished)
Кажется вот эта штука должна вызываться в set для property IsFinished. Кажется тут ещё не хватает состояния модели, что типа это LAST_TURN. Чтобы отличать, что это уже history или только играть закончили и надо показать инфу всякую. Подумай, можешь ли его реализовать без сервера как-то. Может быть в set можно получить предыдущее состояние переменной. И типа если она была false, а при set ей говорят стать true, то как раз вызывать отображалку конца. Возможно имеет смысл ввести ещё один property, который как раз автоматически становится true при изменении IsFinished с true на false, а при остальных изменениях становится false.

2021-03-30 10:26 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +        public void UpdateField()
Лучше, наверное, назвать UpdateGameField, а то я умудрился спутать с TextField

2021-03-30 10:26 UTC, mike-live commented on RWGame/RWGame/ViewModels/GameFieldViewModel.cs
> +            GameFieldModel.FillGameTrajectory();
Почему нельзя fill сделать в модельке?

2021-03-30 10:26 UTC, mike-live commented on RWGame/RWGame/Views/GameField.xaml.cs
> +            if (ViewModel.GameStateInfo.GameState == GameStateEnum.WAIT)
Ок, я подумаю тогда в следующей итерации, как решить.

2021-03-30 10:29 UTC, mike-live commented on RWGame/RWGame/Models/GameFieldModel.cs
> +                GameTrajectory.Add(new SKPoint(turn.State[0], turn.State[1]));
Наверное, давай заведём всё таки свой class Point {x, y} для модельки. Чтобы отвязать её от skia. А там, где отрисовка они кастанут в SKPoint.

2021-03-30 12:03 UTC, SermanVS commented on RWGame/RWGame.iOS/RWGame.iOS.csproj
> +    <CodesignKey>Apple Development: Sergei Tikhomirov (S99WRDW6YL)</CodesignKey>
Вроде нет, в Open Source проектах на Xamarion iOS у них стоит iPhone Developer везде

2021-03-30 12:05 UTC, SermanVS commented on RWGame/RWGame/ViewModels/GameFieldViewModel.cs
> +            GameScoreLabelText = GameFieldModel.NumTurns.ToString();
Так не работает через проперти, Fody не обновляет их, когда надо. Единственное решение, которое я нашёл - это сделать так. Если посмотреть другие ViewModel, то там абсолютно такая же ситуация

2021-03-30 12:08 UTC, SermanVS commented on RWGame/RWGame/ViewModels/GameFieldViewModel.cs
> +            GameFieldModel.FillGameTrajectory();
Ну он и делается в модельке. Если в конструкторе модели вызывать Fill, то всё упадет, т.к. для ViewModel объект модельки ещё не создался, а к нему при Fill будут обращаться и просить с него траекторию.

2021-03-30 12:32 UTC, SermanVS commented on RWGame/RWGame/ViewModels/GameFieldViewModel.cs
> +            InfoTurnLabelText = InfoStringsEnum.WAIT.ToDescriptionString();
Это для GameControls прокидывается, чтобы вызывалось там в нужном месте. Не знаю, как это иначе реализовать

2021-03-30 12:51 UTC, mike-live commented on RWGame/RWGame/ViewModels/GameFieldViewModel.cs
> +            GameFieldModel.FillGameTrajectory();
Я не понял. У тебя и сейчас на 226ой строке ещё не создалась ViewModel. Что поменяется?

2021-03-30 12:59 UTC, mike-live commented
Кажется ещё нет файлика InfoStrings.cs

2021-03-30 13:00 UTC, SermanVS commented on RWGame/RWGame/ViewModels/GameFieldViewModel.cs
> +            GameFieldModel.FillGameTrajectory();
Не создался ViewModel, но создался Model. Т.е. начиная с 220 строчки 
            GameFieldModel = new GameFieldModel(UpdateFieldState);
можно обращаться к Model, она готова. FillGameTrajectory() использует Game, который прокидывается в модель через property из ViewModel. Т.е. сама модель ещё не наполнена данными в момент создания, а мы уже хотим к ним обратиться. Поэтому сначала мы создаем модель, потом заполняем (Game = game, GameStateInfo = gameStateInfo) и только потом просим её сделать FillGameTrajectory()

2021-03-30 13:07 UTC, mike-live commented on RWGame/RWGame/ViewModels/GameFieldViewModel.cs
> +            GameFieldModel.FillGameTrajectory();
Так ты передай game в конструктор модели

2021-03-30 15:16 UTC, SermanVS commented on RWGame/RWGame/ViewModels/GameFieldViewModel.cs
> +            if (IsFinished)
Не выйдет, т.к. там идёт await. Я сделал отдельным методом

2021-04-02 13:22 UTC, merged